name: flutterdemo
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  html: ^0.15.1
  easy_refresh: ^3.3.0+1
  cached_network_image: ^3.2.3
  flutter_js: ^0.6.0
  video_player: ^2.5.1
  dio_cookie_manager: ^2.0.0
  flutter_spinkit: ^5.1.0
  flutter_easyloading: ^3.0.5
  fijkplayer: ^0.10.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true
